// apps/vue-demo/src/Card.vue

<script lang="ts" setup>
import stylex from "@stylexjs/stylex";
import { tokens } from "./theme.stylex";
</script>

<script lang="ts">
const styles = stylex.create({
  root: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 16,
    boxShadow: "0 0 16px rgba(0, 0, 0, 0.1)",
    color: tokens.primaryTextColor,
  },
});
</script>

<template>
  <div :class="stylex(styles.root)" data-testid="card">
    <slot />
  </div>
</template>

// apps/remix-demo/app/Card.tsx
import * as stylex from "@stylexjs/stylex";
import { tokens } from "./theme.stylex";

export default function Card({ children }: { children: React.ReactNode }) {
  return (
    <div {...stylex.props(styles.root)} data-testid="card">
      {children}
    </div>
  );
}

const styles = stylex.create({
  root: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 16,
    boxShadow: "0 0 16px rgba(0, 0, 0, 0.1)",
    color: tokens.primaryTextColor,
  },
});
